---
title: "endemism_genera_summary"
format: html
editor: visual
---

```{r}
library(tidyverse)
summary <- read_csv('intermediate_data/five_sources_summary.csv')

unclear <- summary[summary$current_knowledge == 'unclear', ]
unclear$reason <- NA


```

```{r}
unclear$genus

unclear$current_knowledge[1] <- 'endemic' 
unclear$reason[1] <- 'ALA taxonomy error'

unclear$current_knowledge[2] <- 'non-endemic' 
unclear$reason[2] <- 'taxonomy error'


unclear$current_knowledge[3] <- 'endemic' 
unclear$reason[3] <- 'POWO data error'

unclear$reason[4] <- 'records from 1950s, PNG occurence uncertain'

unclear$current_knowledge[5] <- 'endemic' 
unclear$reason[5] <- 'POWO data error'

unclear$current_knowledge[6] <- 'endemic'
unclear$reason[6] <- 'Indo data error'

unclear$current_knowledge[7] <- 'endemic'
unclear$reason[7] <- 'POWO data error'

unclear$current_knowledge[8] <- 'non-endemic'
unclear$reason[8] <- 'NC occurence'

unclear$current_knowledge[9] <- 'non-endemic'
unclear$reason[9] <- 'taxonomic error - synonym Machaerina used'

unclear$current_knowledge[10] <- 'non-endemic'
unclear$reason[10] <- 'PNG native'

unclear$current_knowledge[11] <- 'endemic'
unclear$reason[11] <- 'ALA data/shapefile error'

unclear$current_knowledge[12] <- 'endemic'
unclear$reason[12] <- 'ALA data/shapefile error'

unclear$current_knowledge[13] <- 'endemic'
unclear$reason[13] <- 'ornamental plant in UK'

unclear$current_knowledge[14] <- 'unclear'
unclear$reason[14] <- 'taxonomic uncertainty - WCVP says 4 species, zimbabwe flora mentions only 1 accepted species'

unclear$current_knowledge[15] <- 'endemic'
unclear$reason[15] <- 'ng data error'

unclear$current_knowledge[16] <- 'non-endemic'
unclear$reason[16] <- 'taxonomy error, NZ species'

unclear$current_knowledge[17] <- 'unclear'
unclear$reason[17] <- 'introduced NZ and California'

unclear$current_knowledge[18] <- 'unclear'
unclear$reason[18] <- 'introduced India'

unclear$current_knowledge[19] <- 'non-endemic'
unclear$reason[19] <- 'species found in South America'

unclear$current_knowledge[20] <- 'unclear'
unclear$reason[20] <- 'introduced ornamentals in UK'

unclear$current_knowledge[21] <- 'non-endemic'
unclear$reason[21] <- 'species found in Africa, Americas, South Asia etc'

unclear$current_knowledge[22] <- 'endemic'
unclear$reason[22] <- 'taxonomic confusion, tasmania only'

unclear$current_knowledge[23] <- 'non-endemic'
unclear$reason[23] <- 'species found in Africa, Americas, South Asia etc'



unclear$genus[24] 

```
